### ISSUE TITLE
about the init_prompt_pair.pth

### ISSUE THREAD

**Issue by diadestiny** [ZhexinLiang/CLIP-LIT#4]
Thanks for your work!
I want to know how 'init_prompt_pair.pth' is obtained, especially the 'embedding_prompt' key. Is there any relevant source for this pth file?

**Comment by jiaqixuac** [comment]
Thank you for your nice work!

I also want to know if the training code for the initial prompt has been released.

**Comment by ZhexinLiang** [comment]
Hi, thanks for your interest.

You can use the following command to train from scratch, that is, training without 'init_prompt_pair.pth' and 'init_enhancement_model.pth'.
```
python train.py --num_reconstruction_iters 1000 --num_clip_pretrained_iters 8000 --load_pretrain False --load_pretrain_prompt False
```
Using this line, the first 8000 iterations will learn the initial prompt pair, and the following 1000 iterations will learn the initial enhancement network. And after the initialization, the fine-tuning will start.
