### ISSUE TITLE
About the prompt and model initialization

### ISSUE THREAD

**Issue by jiaqixuac** [ZhexinLiang/CLIP-LIT#5]
Hi,
Thank you for your nice work.
I want to know if it is possible not using the provided initial prompt and enhancement model but to train from scratch by using
```
python train.py -b ./train_data/BAID_380/resize_input/ -r ./train_data/DIV2K_384/ \
--load_pretrain False --load_pretrain_prompt False --num_reconstruction_iters 1000 --num_clip_pretrained_iters 8000
```

**Comment by ZhexinLiang** [comment]
Hi, thanks for your interest.

Yes, you can use this command to train from scratch. :)

Btw, I updated the train.py. The old version may have some memory issues if you use it to train from scratch. Please download the latest version. Sorry for the inconvenience caused.
