### ISSUE TITLE
about tarinning log

### ISSUE THREAD

**Issue by faicaiwawa** [ZhexinLiang/CLIP-LIT#9]
Hi, very interesting work! 
Would it be convenient to provide a loss log for training, I'm having some problems with the training process when using this method in other directions, thanks!

**Comment by ZhexinLiang** [comment]
Hi @faicaiwawa, thanks for your interest in our work.

Apologies for my delayed response. I think I have deleted the training log. I cannot find it anymore. I will rerun the experiment and give you the loss log within the next two weeks. I have been quite busy recently. Apologize again for my late response.

**Comment by faicaiwawa** [comment]
> Hi @faicaiwawa, thanks for your interest in our work.
> 
> Apologies for my delayed response. I think I have deleted the training log. I cannot find it anymore. I will rerun the experiment and give you the loss log within the next two weeks. I have been quite busy recently. Apologize again for my late response.

Thanks for your reply, I've fixed the problem so you don't have to spend time re-experimenting.

**Comment by ZhexinLiang** [comment]
I provide the training logs at issue #15 .
